services:
  client:
    image: burpple_frontend
    container_name: burpple_frontend_container
    depends_on:
      - server
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - BACKEND_URL=http://server:5000

  server:
    image: burpple_backend
    container_name: burpple_backend_container
    depends_on:
      - database
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      # these env keys have to be set for deployment.
      # the values used below are for production simulation purpose.
      # for more details, refer to `./.env.prod`.
      - APP_DATABASE__USERNAME=postgres
      - APP_DATABASE__PASSWORD=password
      - APP_DATABASE__HOST=database
      - APP_DATABASE__PORT=5432
      - APP_DATABASE__REQUIRE_SSL=false # remove this env when in actual prod environment.
      - APP_APPLICATION__request_origin=http://client:3000

  database:
    image: postgres:latest
    container_name: burpple_psql_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=burpple
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
